services:
  - type: web
    name: lar-doce-app-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    plan: free
    envVars:
      - key: RENDER
        value: "true"
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: tarefa-casa
          property: connectionString